import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import './globals.css';

import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { PopupWidget } from '@/components/PopupWidget';
import DocMoviAssistant from '@/components/DocMoviAssistant';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Navbar />
          <div>{children}</div>
          <Footer />
          <PopupWidget />
          <script src="https://cdn.botpress.cloud/webchat/v2.1/inject.js"></script>
          <script src="https://mediafiles.botpress.cloud/bf12f5c9-d9f6-4b23-a11c-6050f17fe9b5/webchat/v2.1/config.js"></script>
        </ThemeProvider>
      </body>
    </html>
  );
}
